### ISSUE TITLE
conversation_started reply

### ISSUE THREAD

**Issue by yarkm13** [polyskalov/botman-viber-driver#1]
Viber `conversation_started` event let you [send a welcome message](https://developers.viber.com/rest/#SendingWelcomeMessage) to user who not subscribed yet by replying to `conversation_started` webhook call.
Is it implemented/possible with botman?

**Comment by polyskalov** [comment]
Yep

Just ` $bot->say('message')` in `conversation_started` hook


```php
$botman->on(
    'conversation_started',
    static function (array $payload, \BotMan\BotMan\BotMan $bot) {
        $viberId = $payload['user']['id'] ?? null;

        $bot->say('hi',
                $viberId,
                \TheArdent\Drivers\Viber\ViberDriver::class
            );
    }
);

```
