### ISSUE TITLE
Error in ViberDriver.php file

### ISSUE THREAD

**Issue by rajendrap123** [polyskalov/botman-viber-driver#2]
I am getting below error:

`[2020-06-10 08:37:30] production.ERROR: Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /var/www/aayo.express/aayosathi/vendor/polyskalov/botman-viber-driver/src/ViberDriver.php:296)
[stacktrace]
#0 /var/www/aayo.express/aayosathi/vendor/polyskalov/botman-viber-driver/src/ViberDriver.php(296): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/aayo.express/aayosathi/vendor/botman/botman/src/BotMan.php(237): TheArdent\\Drivers\\Viber\\ViberDriver->getUser()
#2 /var/www/aayo.express/aayosathi/routes/botman.php(34): BotMan\\BotMan\\BotMan->getUser()
#3 [internal function]: App\\Providers\\RouteServiceProvider->{closure}()
#4 /var/www/aayo.express/aayosathi/vendor/botman/botman/src/BotMan.php(495): call_user_func_array()
#5 /var/www/aayo.express/aayosathi/vendor/botman/botman/src/BotMan.php(425): BotMan\\BotMan\\BotMan->callMatchingMessages()
#6 /var/www/aayo.express/aayosathi/app/Http/Controllers/BotManController.php(18): BotMan\\BotMan\\BotMan->listen()
#7 [internal function]: App\\Http\\Controllers\\BotManController->handle()
#8 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#9 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#10 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#11 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#12 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#13 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#14 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#15 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#16 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#18 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#19 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#21 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#22 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#24 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle()
#25 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#27 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#28 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#30 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#31 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#33 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then()
#34 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack()
#35 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute()
#36 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute()
#37 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#38 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#39 /var/www/aayo.express/aayosathi/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#40 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle()
#41 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#42 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#43 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#44 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#46 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#47 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#49 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#50 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#52 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#53 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#55 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#56 /var/www/aayo.express/aayosathi/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#57 /var/www/aayo.express/aayosathi/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle()
#58 {main}
"} 
`

any idea why it might be causing it?

**Comment by rajendrap123** [comment]
@polyskalov  can you look into this?

**Comment by rajendrap123** [comment]
@polyskalov 

I see this error is coming when we try to get userinfo, can you pls have look into this?

Thanks

**Comment by polyskalov** [comment]
Sorry for the long answer. I'll look at it today

**Comment by rajendrap123** [comment]
@polyskalov 

thanks, waiting for it to be resolved :)

**Comment by rajendrap123** [comment]
@polyskalov 

any update on this?

thanks
