### ISSUE TITLE
How to save viber_id of user to database?

### ISSUE THREAD

**Issue by rajendrap123** [polyskalov/botman-viber-driver#3]
@polyskalov 

Thanks for this great package.

I would like to know how to save users viber_ids to database, so that we can send messages to users later?

Can you please point me to right direction for it?

Cheers

**Comment by polyskalov** [comment]
in routes/botman.php
```php
$botman->on(
    'conversation_started',
    static function (array $payload, BotMan $bot) {
        $viberId = $payload['user']['id'] ?? null;
    }
);
```

**Comment by rajendrap123** [comment]
@polyskalov 

Amazing man, greatly appreciated thank you very much for putting time for this help.

I have a small suggestion, can we have a viber notification channel to send notifications to system users to viber after they subscribe to feature?

**Comment by rajendrap123** [comment]
Hello @polyskalov 

I tried to register the event listener, the way you mentioned.

`$botman->on(
    'conversation_started',
    static function (array $payload, BotMan $bot) {
        $viberId = $payload['user']['id'] ?? null;
    }
);`

But events callback are not being called? 

Can you please let me know what possible cause for it may be? I have checked the logs and not any log found it in.

**Comment by rajendrap123** [comment]
Hello @polyskalov 

I think i am getting this error on events:

`[2020-06-12 08:54:08] production.ERROR: Trying to access array offset on value of type null {"exception":"[object] (ErrorException(code: 0): Trying to access array offset on value of type null at /var/www/aayo.express/aayosathi/vendor/polyskalov/botman-viber-driver/src/ViberDriver.php:163)`

Can you pls look into it?

Thanks

**Comment by rajendrap123** [comment]
@polyskalov 

Can you please guide me in the right direction for the below point:

I am now able to get the viber id, but as i have laravel app, i want to associate this `viber_id` to `App\User` model?

How do we associate viber id to its user? any clue?

Thanks in advance.

**Comment by rajendrap123** [comment]
Update on above code:

`$botman->on(
    'conversation_started',
    static function (array $payload, BotMan $bot) {
        $viberId = $payload['user_id'] ?? null';

       

    }
);`

**Comment by polyskalov** [comment]
I looked it up. I was wrong, it's the right solution:
`$viberId = $payload['user']['id']`

In this variable there will be a string identifier, which must be correlated with the User model

**Comment by polyskalov** [comment]
**Package updated** with bug fixing
Please check [v1.1](https://github.com/polyskalov/botman-viber-driver/releases/tag/v1.1)


> I have a small suggestion, can we have a viber notification channel

Maybe later, no time for now



> How to save to database

As I mentioned earlier, you can use the user ID from the event and then manipulate it as you wish. Add to the database, for example (User model need to have `viber_id` field):

```php
$botman->on(
    'conversation_started',
    static function (array $payload, BotMan $bot) {
        $user = \App\User::updateOrCreate(
            [
                'viber_id' => $bot->getUser()->getId()
            ],
            [
                'name' => $bot->getUser()->getUsername()
            ]
        );
    }
);
```

(`$bot->getUser()` is the replacement for `$payload['user']['id'] ?? null`)

**Comment by rajendrap123** [comment]
thanks
